// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrbrflygrfazureptxfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyYnJmbHlncmZhenVyZXB0eGZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwNTE5NjgsImV4cCI6MjA1OTYyNzk2OH0.bZEs4zgBG8Ib9tfbKal4HYkdIthYPddXAJA7hAaaxuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);